### ISSUE TITLE
Allow user to set a custom upDev username

### ISSUE THREAD

**Issue by MattPereira** [bshevchenko/updev#60]
### Overview
Currently, the primary username matches the lukso UP "name". We want to allow users to edit their upDev username as they please by adding a "username" key/value pair to the UP contract deployed on Mumbai

![image](https://github.com/DeezStealth/updev/assets/73561520/068ee0fb-7c24-4733-9e65-57081ff55b54)

### Tasks
- [x] Add edit icon button next to upDev username
- [x] Figure out input field and pre-populate it with either UP name or upDev username (if it exists)
- [x] After user edits their upDev username, fire `setData` transaction and update UI

### Resources
- https://docs.lukso.tech/contracts/contracts/UniversalProfile/#setdata
- https://docs.lukso.tech/contracts/contracts/LSP0ERC725Account/#getdata

**Comment by bshevchenko** [comment]
@MattPereira thanks! I'll review your PR shortly. I wouldn't really call that username tho, that is user's firstname+lastname (is there a one simple word for that?). But you gave me an idea, that we should probably make more user-friendly URLs to users profile pages, like: https://updev-v1.vercel.app/mattpereira
@tantodefi

**Comment by MattPereira** [comment]
@bshevchenko I'm not sure if asking or forcing user to disclose their first and last name vibes with our target audience of web3 natives many of whom prefer to remain anon like @tantodefi 

Definitely agree with the idea to make URL more user friendly but would that throw a wrench in your backend logic for on chain verification of social account ownership ?

![image](https://github.com/DeezStealth/updev/assets/73561520/af7d4f90-f33a-4d19-821e-ab4a31224abe)

**Comment by bshevchenko** [comment]
@MattPereira that feature is optional. but how can you imagine a good CV/resumve without even a real name on it?)

@MattPereira yeah username URLs will require some additional solution, I'll create a separate issue for it now
